// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/common_local_cache.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "common_local_cache.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace vip {
namespace local {
namespace cache {
namespace proto {
class CacheCommandDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<CacheCommand> {
} _CacheCommand_default_instance_;

namespace protobuf_protocol_2fcommon_5flocal_5fcache_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CacheCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CacheCommand, messagetype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CacheCommand, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CacheCommand, value_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CacheCommand, parameter_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(CacheCommand)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_CacheCommand_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "protocol/common_local_cache.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _CacheCommand_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _CacheCommand_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n!protocol/common_local_cache.proto\022\031com"
      ".vip.local.cache.proto\"R\n\014CacheCommand\022\023"
      "\n\013messageType\030\001 \001(\005\022\013\n\003key\030\002 \001(\t\022\r\n\005valu"
      "e\030\003 \001(\014\022\021\n\tparameter\030\004 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 154);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protocol/common_local_cache.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_protocol_2fcommon_5flocal_5fcache_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CacheCommand::kMessageTypeFieldNumber;
const int CacheCommand::kKeyFieldNumber;
const int CacheCommand::kValueFieldNumber;
const int CacheCommand::kParameterFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CacheCommand::CacheCommand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_protocol_2fcommon_5flocal_5fcache_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.vip.local.cache.proto.CacheCommand)
}
CacheCommand::CacheCommand(const CacheCommand& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value().size() > 0) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  parameter_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.parameter().size() > 0) {
    parameter_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.parameter_);
  }
  messagetype_ = from.messagetype_;
  // @@protoc_insertion_point(copy_constructor:com.vip.local.cache.proto.CacheCommand)
}

void CacheCommand::SharedCtor() {
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  parameter_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  messagetype_ = 0;
  _cached_size_ = 0;
}

CacheCommand::~CacheCommand() {
  // @@protoc_insertion_point(destructor:com.vip.local.cache.proto.CacheCommand)
  SharedDtor();
}

void CacheCommand::SharedDtor() {
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  parameter_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CacheCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CacheCommand::descriptor() {
  protobuf_protocol_2fcommon_5flocal_5fcache_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_protocol_2fcommon_5flocal_5fcache_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CacheCommand& CacheCommand::default_instance() {
  protobuf_protocol_2fcommon_5flocal_5fcache_2eproto::InitDefaults();
  return *internal_default_instance();
}

CacheCommand* CacheCommand::New(::google::protobuf::Arena* arena) const {
  CacheCommand* n = new CacheCommand;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CacheCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:com.vip.local.cache.proto.CacheCommand)
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  parameter_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  messagetype_ = 0;
}

bool CacheCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.vip.local.cache.proto.CacheCommand)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 messageType = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &messagetype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string key = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), this->key().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.vip.local.cache.proto.CacheCommand.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes value = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string parameter = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_parameter()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->parameter().data(), this->parameter().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.vip.local.cache.proto.CacheCommand.parameter"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.vip.local.cache.proto.CacheCommand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.vip.local.cache.proto.CacheCommand)
  return false;
#undef DO_
}

void CacheCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.vip.local.cache.proto.CacheCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 messageType = 1;
  if (this->messagetype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->messagetype(), output);
  }

  // string key = 2;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.vip.local.cache.proto.CacheCommand.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->key(), output);
  }

  // bytes value = 3;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->value(), output);
  }

  // string parameter = 4;
  if (this->parameter().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->parameter().data(), this->parameter().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.vip.local.cache.proto.CacheCommand.parameter");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->parameter(), output);
  }

  // @@protoc_insertion_point(serialize_end:com.vip.local.cache.proto.CacheCommand)
}

::google::protobuf::uint8* CacheCommand::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.vip.local.cache.proto.CacheCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 messageType = 1;
  if (this->messagetype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->messagetype(), target);
  }

  // string key = 2;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.vip.local.cache.proto.CacheCommand.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->key(), target);
  }

  // bytes value = 3;
  if (this->value().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->value(), target);
  }

  // string parameter = 4;
  if (this->parameter().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->parameter().data(), this->parameter().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.vip.local.cache.proto.CacheCommand.parameter");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->parameter(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:com.vip.local.cache.proto.CacheCommand)
  return target;
}

size_t CacheCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.vip.local.cache.proto.CacheCommand)
  size_t total_size = 0;

  // string key = 2;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  // bytes value = 3;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->value());
  }

  // string parameter = 4;
  if (this->parameter().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->parameter());
  }

  // int32 messageType = 1;
  if (this->messagetype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->messagetype());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CacheCommand::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.vip.local.cache.proto.CacheCommand)
  GOOGLE_DCHECK_NE(&from, this);
  const CacheCommand* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CacheCommand>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.vip.local.cache.proto.CacheCommand)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.vip.local.cache.proto.CacheCommand)
    MergeFrom(*source);
  }
}

void CacheCommand::MergeFrom(const CacheCommand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.vip.local.cache.proto.CacheCommand)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  if (from.parameter().size() > 0) {

    parameter_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.parameter_);
  }
  if (from.messagetype() != 0) {
    set_messagetype(from.messagetype());
  }
}

void CacheCommand::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.vip.local.cache.proto.CacheCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CacheCommand::CopyFrom(const CacheCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.vip.local.cache.proto.CacheCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CacheCommand::IsInitialized() const {
  return true;
}

void CacheCommand::Swap(CacheCommand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CacheCommand::InternalSwap(CacheCommand* other) {
  key_.Swap(&other->key_);
  value_.Swap(&other->value_);
  parameter_.Swap(&other->parameter_);
  std::swap(messagetype_, other->messagetype_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CacheCommand::GetMetadata() const {
  protobuf_protocol_2fcommon_5flocal_5fcache_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_protocol_2fcommon_5flocal_5fcache_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CacheCommand

// int32 messageType = 1;
void CacheCommand::clear_messagetype() {
  messagetype_ = 0;
}
::google::protobuf::int32 CacheCommand::messagetype() const {
  // @@protoc_insertion_point(field_get:com.vip.local.cache.proto.CacheCommand.messageType)
  return messagetype_;
}
void CacheCommand::set_messagetype(::google::protobuf::int32 value) {
  
  messagetype_ = value;
  // @@protoc_insertion_point(field_set:com.vip.local.cache.proto.CacheCommand.messageType)
}

// string key = 2;
void CacheCommand::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CacheCommand::key() const {
  // @@protoc_insertion_point(field_get:com.vip.local.cache.proto.CacheCommand.key)
  return key_.GetNoArena();
}
void CacheCommand::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.vip.local.cache.proto.CacheCommand.key)
}
#if LANG_CXX11
void CacheCommand::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.vip.local.cache.proto.CacheCommand.key)
}
#endif
void CacheCommand::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.vip.local.cache.proto.CacheCommand.key)
}
void CacheCommand::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.vip.local.cache.proto.CacheCommand.key)
}
::std::string* CacheCommand::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:com.vip.local.cache.proto.CacheCommand.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CacheCommand::release_key() {
  // @@protoc_insertion_point(field_release:com.vip.local.cache.proto.CacheCommand.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CacheCommand::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:com.vip.local.cache.proto.CacheCommand.key)
}

// bytes value = 3;
void CacheCommand::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CacheCommand::value() const {
  // @@protoc_insertion_point(field_get:com.vip.local.cache.proto.CacheCommand.value)
  return value_.GetNoArena();
}
void CacheCommand::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.vip.local.cache.proto.CacheCommand.value)
}
#if LANG_CXX11
void CacheCommand::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.vip.local.cache.proto.CacheCommand.value)
}
#endif
void CacheCommand::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.vip.local.cache.proto.CacheCommand.value)
}
void CacheCommand::set_value(const void* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.vip.local.cache.proto.CacheCommand.value)
}
::std::string* CacheCommand::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:com.vip.local.cache.proto.CacheCommand.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CacheCommand::release_value() {
  // @@protoc_insertion_point(field_release:com.vip.local.cache.proto.CacheCommand.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CacheCommand::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:com.vip.local.cache.proto.CacheCommand.value)
}

// string parameter = 4;
void CacheCommand::clear_parameter() {
  parameter_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& CacheCommand::parameter() const {
  // @@protoc_insertion_point(field_get:com.vip.local.cache.proto.CacheCommand.parameter)
  return parameter_.GetNoArena();
}
void CacheCommand::set_parameter(const ::std::string& value) {
  
  parameter_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.vip.local.cache.proto.CacheCommand.parameter)
}
#if LANG_CXX11
void CacheCommand::set_parameter(::std::string&& value) {
  
  parameter_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.vip.local.cache.proto.CacheCommand.parameter)
}
#endif
void CacheCommand::set_parameter(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  parameter_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.vip.local.cache.proto.CacheCommand.parameter)
}
void CacheCommand::set_parameter(const char* value, size_t size) {
  
  parameter_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.vip.local.cache.proto.CacheCommand.parameter)
}
::std::string* CacheCommand::mutable_parameter() {
  
  // @@protoc_insertion_point(field_mutable:com.vip.local.cache.proto.CacheCommand.parameter)
  return parameter_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* CacheCommand::release_parameter() {
  // @@protoc_insertion_point(field_release:com.vip.local.cache.proto.CacheCommand.parameter)
  
  return parameter_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void CacheCommand::set_allocated_parameter(::std::string* parameter) {
  if (parameter != NULL) {
    
  } else {
    
  }
  parameter_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), parameter);
  // @@protoc_insertion_point(field_set_allocated:com.vip.local.cache.proto.CacheCommand.parameter)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace cache
}  // namespace local
}  // namespace vip
}  // namespace com

// @@protoc_insertion_point(global_scope)
