// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/common_local_cache.proto

#ifndef PROTOBUF_protocol_2fcommon_5flocal_5fcache_2eproto__INCLUDED
#define PROTOBUF_protocol_2fcommon_5flocal_5fcache_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace com {
namespace vip {
namespace local {
namespace cache {
namespace proto {
class CacheCommand;
class CacheCommandDefaultTypeInternal;
extern CacheCommandDefaultTypeInternal _CacheCommand_default_instance_;
}  // namespace proto
}  // namespace cache
}  // namespace local
}  // namespace vip
}  // namespace com

namespace com {
namespace vip {
namespace local {
namespace cache {
namespace proto {

namespace protobuf_protocol_2fcommon_5flocal_5fcache_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_protocol_2fcommon_5flocal_5fcache_2eproto

// ===================================================================

class CacheCommand : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.vip.local.cache.proto.CacheCommand) */ {
 public:
  CacheCommand();
  virtual ~CacheCommand();

  CacheCommand(const CacheCommand& from);

  inline CacheCommand& operator=(const CacheCommand& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CacheCommand& default_instance();

  static inline const CacheCommand* internal_default_instance() {
    return reinterpret_cast<const CacheCommand*>(
               &_CacheCommand_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CacheCommand* other);

  // implements Message ----------------------------------------------

  inline CacheCommand* New() const PROTOBUF_FINAL { return New(NULL); }

  CacheCommand* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CacheCommand& from);
  void MergeFrom(const CacheCommand& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CacheCommand* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string key = 2;
  void clear_key();
  static const int kKeyFieldNumber = 2;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // bytes value = 3;
  void clear_value();
  static const int kValueFieldNumber = 3;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const void* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // string parameter = 4;
  void clear_parameter();
  static const int kParameterFieldNumber = 4;
  const ::std::string& parameter() const;
  void set_parameter(const ::std::string& value);
  #if LANG_CXX11
  void set_parameter(::std::string&& value);
  #endif
  void set_parameter(const char* value);
  void set_parameter(const char* value, size_t size);
  ::std::string* mutable_parameter();
  ::std::string* release_parameter();
  void set_allocated_parameter(::std::string* parameter);

  // int32 messageType = 1;
  void clear_messagetype();
  static const int kMessageTypeFieldNumber = 1;
  ::google::protobuf::int32 messagetype() const;
  void set_messagetype(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.vip.local.cache.proto.CacheCommand)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  ::google::protobuf::internal::ArenaStringPtr parameter_;
  ::google::protobuf::int32 messagetype_;
  mutable int _cached_size_;
  friend struct protobuf_protocol_2fcommon_5flocal_5fcache_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CacheCommand

// int32 messageType = 1;
inline void CacheCommand::clear_messagetype() {
  messagetype_ = 0;
}
inline ::google::protobuf::int32 CacheCommand::messagetype() const {
  // @@protoc_insertion_point(field_get:com.vip.local.cache.proto.CacheCommand.messageType)
  return messagetype_;
}
inline void CacheCommand::set_messagetype(::google::protobuf::int32 value) {
  
  messagetype_ = value;
  // @@protoc_insertion_point(field_set:com.vip.local.cache.proto.CacheCommand.messageType)
}

// string key = 2;
inline void CacheCommand::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CacheCommand::key() const {
  // @@protoc_insertion_point(field_get:com.vip.local.cache.proto.CacheCommand.key)
  return key_.GetNoArena();
}
inline void CacheCommand::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.vip.local.cache.proto.CacheCommand.key)
}
#if LANG_CXX11
inline void CacheCommand::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.vip.local.cache.proto.CacheCommand.key)
}
#endif
inline void CacheCommand::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.vip.local.cache.proto.CacheCommand.key)
}
inline void CacheCommand::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.vip.local.cache.proto.CacheCommand.key)
}
inline ::std::string* CacheCommand::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:com.vip.local.cache.proto.CacheCommand.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CacheCommand::release_key() {
  // @@protoc_insertion_point(field_release:com.vip.local.cache.proto.CacheCommand.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CacheCommand::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:com.vip.local.cache.proto.CacheCommand.key)
}

// bytes value = 3;
inline void CacheCommand::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CacheCommand::value() const {
  // @@protoc_insertion_point(field_get:com.vip.local.cache.proto.CacheCommand.value)
  return value_.GetNoArena();
}
inline void CacheCommand::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.vip.local.cache.proto.CacheCommand.value)
}
#if LANG_CXX11
inline void CacheCommand::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.vip.local.cache.proto.CacheCommand.value)
}
#endif
inline void CacheCommand::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.vip.local.cache.proto.CacheCommand.value)
}
inline void CacheCommand::set_value(const void* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.vip.local.cache.proto.CacheCommand.value)
}
inline ::std::string* CacheCommand::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:com.vip.local.cache.proto.CacheCommand.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CacheCommand::release_value() {
  // @@protoc_insertion_point(field_release:com.vip.local.cache.proto.CacheCommand.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CacheCommand::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:com.vip.local.cache.proto.CacheCommand.value)
}

// string parameter = 4;
inline void CacheCommand::clear_parameter() {
  parameter_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CacheCommand::parameter() const {
  // @@protoc_insertion_point(field_get:com.vip.local.cache.proto.CacheCommand.parameter)
  return parameter_.GetNoArena();
}
inline void CacheCommand::set_parameter(const ::std::string& value) {
  
  parameter_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.vip.local.cache.proto.CacheCommand.parameter)
}
#if LANG_CXX11
inline void CacheCommand::set_parameter(::std::string&& value) {
  
  parameter_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.vip.local.cache.proto.CacheCommand.parameter)
}
#endif
inline void CacheCommand::set_parameter(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  parameter_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.vip.local.cache.proto.CacheCommand.parameter)
}
inline void CacheCommand::set_parameter(const char* value, size_t size) {
  
  parameter_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.vip.local.cache.proto.CacheCommand.parameter)
}
inline ::std::string* CacheCommand::mutable_parameter() {
  
  // @@protoc_insertion_point(field_mutable:com.vip.local.cache.proto.CacheCommand.parameter)
  return parameter_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CacheCommand::release_parameter() {
  // @@protoc_insertion_point(field_release:com.vip.local.cache.proto.CacheCommand.parameter)
  
  return parameter_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CacheCommand::set_allocated_parameter(::std::string* parameter) {
  if (parameter != NULL) {
    
  } else {
    
  }
  parameter_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), parameter);
  // @@protoc_insertion_point(field_set_allocated:com.vip.local.cache.proto.CacheCommand.parameter)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace proto
}  // namespace cache
}  // namespace local
}  // namespace vip
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protocol_2fcommon_5flocal_5fcache_2eproto__INCLUDED
