// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol/shared_memory_struct.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "shared_memory_struct.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace com {
namespace vip {
namespace local {
namespace cache {
namespace proto {
class SharedMemoryObjectDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<SharedMemoryObject> {
} _SharedMemoryObject_default_instance_;

namespace protobuf_protocol_2fshared_5fmemory_5fstruct_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SharedMemoryObject, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SharedMemoryObject, ip_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SharedMemoryObject, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SharedMemoryObject, value_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SharedMemoryObject, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SharedMemoryObject, optype_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(SharedMemoryObject)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_SharedMemoryObject_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "protocol/shared_memory_struct.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _SharedMemoryObject_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _SharedMemoryObject_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n#protocol/shared_memory_struct.proto\022\031c"
      "om.vip.local.cache.proto\"_\n\022SharedMemory"
      "Object\022\n\n\002ip\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\022\r\n\005value"
      "\030\003 \001(\t\022\021\n\ttimestamp\030\004 \001(\004\022\016\n\006opType\030\005 \001("
      "\rb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 169);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "protocol/shared_memory_struct.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_protocol_2fshared_5fmemory_5fstruct_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SharedMemoryObject::kIpFieldNumber;
const int SharedMemoryObject::kKeyFieldNumber;
const int SharedMemoryObject::kValueFieldNumber;
const int SharedMemoryObject::kTimestampFieldNumber;
const int SharedMemoryObject::kOpTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SharedMemoryObject::SharedMemoryObject()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_protocol_2fshared_5fmemory_5fstruct_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:com.vip.local.cache.proto.SharedMemoryObject)
}
SharedMemoryObject::SharedMemoryObject(const SharedMemoryObject& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.ip().size() > 0) {
    ip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ip_);
  }
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.key().size() > 0) {
    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value().size() > 0) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  ::memcpy(&timestamp_, &from.timestamp_,
    reinterpret_cast<char*>(&optype_) -
    reinterpret_cast<char*>(&timestamp_) + sizeof(optype_));
  // @@protoc_insertion_point(copy_constructor:com.vip.local.cache.proto.SharedMemoryObject)
}

void SharedMemoryObject::SharedCtor() {
  ip_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&timestamp_, 0, reinterpret_cast<char*>(&optype_) -
    reinterpret_cast<char*>(&timestamp_) + sizeof(optype_));
  _cached_size_ = 0;
}

SharedMemoryObject::~SharedMemoryObject() {
  // @@protoc_insertion_point(destructor:com.vip.local.cache.proto.SharedMemoryObject)
  SharedDtor();
}

void SharedMemoryObject::SharedDtor() {
  ip_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SharedMemoryObject::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SharedMemoryObject::descriptor() {
  protobuf_protocol_2fshared_5fmemory_5fstruct_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_protocol_2fshared_5fmemory_5fstruct_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SharedMemoryObject& SharedMemoryObject::default_instance() {
  protobuf_protocol_2fshared_5fmemory_5fstruct_2eproto::InitDefaults();
  return *internal_default_instance();
}

SharedMemoryObject* SharedMemoryObject::New(::google::protobuf::Arena* arena) const {
  SharedMemoryObject* n = new SharedMemoryObject;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SharedMemoryObject::Clear() {
// @@protoc_insertion_point(message_clear_start:com.vip.local.cache.proto.SharedMemoryObject)
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&timestamp_, 0, reinterpret_cast<char*>(&optype_) -
    reinterpret_cast<char*>(&timestamp_) + sizeof(optype_));
}

bool SharedMemoryObject::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:com.vip.local.cache.proto.SharedMemoryObject)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string ip = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ip()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->ip().data(), this->ip().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.vip.local.cache.proto.SharedMemoryObject.ip"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string key = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_key()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->key().data(), this->key().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.vip.local.cache.proto.SharedMemoryObject.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string value = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value().data(), this->value().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "com.vip.local.cache.proto.SharedMemoryObject.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 timestamp = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 opType = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &optype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:com.vip.local.cache.proto.SharedMemoryObject)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:com.vip.local.cache.proto.SharedMemoryObject)
  return false;
#undef DO_
}

void SharedMemoryObject::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:com.vip.local.cache.proto.SharedMemoryObject)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ip = 1;
  if (this->ip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ip().data(), this->ip().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.vip.local.cache.proto.SharedMemoryObject.ip");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->ip(), output);
  }

  // string key = 2;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.vip.local.cache.proto.SharedMemoryObject.key");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->key(), output);
  }

  // string value = 3;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.vip.local.cache.proto.SharedMemoryObject.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->value(), output);
  }

  // uint64 timestamp = 4;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(4, this->timestamp(), output);
  }

  // uint32 opType = 5;
  if (this->optype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->optype(), output);
  }

  // @@protoc_insertion_point(serialize_end:com.vip.local.cache.proto.SharedMemoryObject)
}

::google::protobuf::uint8* SharedMemoryObject::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:com.vip.local.cache.proto.SharedMemoryObject)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ip = 1;
  if (this->ip().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ip().data(), this->ip().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.vip.local.cache.proto.SharedMemoryObject.ip");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->ip(), target);
  }

  // string key = 2;
  if (this->key().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->key().data(), this->key().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.vip.local.cache.proto.SharedMemoryObject.key");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->key(), target);
  }

  // string value = 3;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), this->value().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "com.vip.local.cache.proto.SharedMemoryObject.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->value(), target);
  }

  // uint64 timestamp = 4;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(4, this->timestamp(), target);
  }

  // uint32 opType = 5;
  if (this->optype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->optype(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:com.vip.local.cache.proto.SharedMemoryObject)
  return target;
}

size_t SharedMemoryObject::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:com.vip.local.cache.proto.SharedMemoryObject)
  size_t total_size = 0;

  // string ip = 1;
  if (this->ip().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ip());
  }

  // string key = 2;
  if (this->key().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->key());
  }

  // string value = 3;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  // uint64 timestamp = 4;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->timestamp());
  }

  // uint32 opType = 5;
  if (this->optype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->optype());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SharedMemoryObject::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:com.vip.local.cache.proto.SharedMemoryObject)
  GOOGLE_DCHECK_NE(&from, this);
  const SharedMemoryObject* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SharedMemoryObject>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:com.vip.local.cache.proto.SharedMemoryObject)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:com.vip.local.cache.proto.SharedMemoryObject)
    MergeFrom(*source);
  }
}

void SharedMemoryObject::MergeFrom(const SharedMemoryObject& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:com.vip.local.cache.proto.SharedMemoryObject)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.ip().size() > 0) {

    ip_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ip_);
  }
  if (from.key().size() > 0) {

    key_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.key_);
  }
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
  if (from.optype() != 0) {
    set_optype(from.optype());
  }
}

void SharedMemoryObject::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:com.vip.local.cache.proto.SharedMemoryObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SharedMemoryObject::CopyFrom(const SharedMemoryObject& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:com.vip.local.cache.proto.SharedMemoryObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SharedMemoryObject::IsInitialized() const {
  return true;
}

void SharedMemoryObject::Swap(SharedMemoryObject* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SharedMemoryObject::InternalSwap(SharedMemoryObject* other) {
  ip_.Swap(&other->ip_);
  key_.Swap(&other->key_);
  value_.Swap(&other->value_);
  std::swap(timestamp_, other->timestamp_);
  std::swap(optype_, other->optype_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SharedMemoryObject::GetMetadata() const {
  protobuf_protocol_2fshared_5fmemory_5fstruct_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_protocol_2fshared_5fmemory_5fstruct_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SharedMemoryObject

// string ip = 1;
void SharedMemoryObject::clear_ip() {
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& SharedMemoryObject::ip() const {
  // @@protoc_insertion_point(field_get:com.vip.local.cache.proto.SharedMemoryObject.ip)
  return ip_.GetNoArena();
}
void SharedMemoryObject::set_ip(const ::std::string& value) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.vip.local.cache.proto.SharedMemoryObject.ip)
}
#if LANG_CXX11
void SharedMemoryObject::set_ip(::std::string&& value) {
  
  ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.vip.local.cache.proto.SharedMemoryObject.ip)
}
#endif
void SharedMemoryObject::set_ip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.vip.local.cache.proto.SharedMemoryObject.ip)
}
void SharedMemoryObject::set_ip(const char* value, size_t size) {
  
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.vip.local.cache.proto.SharedMemoryObject.ip)
}
::std::string* SharedMemoryObject::mutable_ip() {
  
  // @@protoc_insertion_point(field_mutable:com.vip.local.cache.proto.SharedMemoryObject.ip)
  return ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* SharedMemoryObject::release_ip() {
  // @@protoc_insertion_point(field_release:com.vip.local.cache.proto.SharedMemoryObject.ip)
  
  return ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SharedMemoryObject::set_allocated_ip(::std::string* ip) {
  if (ip != NULL) {
    
  } else {
    
  }
  ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip);
  // @@protoc_insertion_point(field_set_allocated:com.vip.local.cache.proto.SharedMemoryObject.ip)
}

// string key = 2;
void SharedMemoryObject::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& SharedMemoryObject::key() const {
  // @@protoc_insertion_point(field_get:com.vip.local.cache.proto.SharedMemoryObject.key)
  return key_.GetNoArena();
}
void SharedMemoryObject::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.vip.local.cache.proto.SharedMemoryObject.key)
}
#if LANG_CXX11
void SharedMemoryObject::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.vip.local.cache.proto.SharedMemoryObject.key)
}
#endif
void SharedMemoryObject::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.vip.local.cache.proto.SharedMemoryObject.key)
}
void SharedMemoryObject::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.vip.local.cache.proto.SharedMemoryObject.key)
}
::std::string* SharedMemoryObject::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:com.vip.local.cache.proto.SharedMemoryObject.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* SharedMemoryObject::release_key() {
  // @@protoc_insertion_point(field_release:com.vip.local.cache.proto.SharedMemoryObject.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SharedMemoryObject::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:com.vip.local.cache.proto.SharedMemoryObject.key)
}

// string value = 3;
void SharedMemoryObject::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& SharedMemoryObject::value() const {
  // @@protoc_insertion_point(field_get:com.vip.local.cache.proto.SharedMemoryObject.value)
  return value_.GetNoArena();
}
void SharedMemoryObject::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.vip.local.cache.proto.SharedMemoryObject.value)
}
#if LANG_CXX11
void SharedMemoryObject::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.vip.local.cache.proto.SharedMemoryObject.value)
}
#endif
void SharedMemoryObject::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.vip.local.cache.proto.SharedMemoryObject.value)
}
void SharedMemoryObject::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.vip.local.cache.proto.SharedMemoryObject.value)
}
::std::string* SharedMemoryObject::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:com.vip.local.cache.proto.SharedMemoryObject.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* SharedMemoryObject::release_value() {
  // @@protoc_insertion_point(field_release:com.vip.local.cache.proto.SharedMemoryObject.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void SharedMemoryObject::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:com.vip.local.cache.proto.SharedMemoryObject.value)
}

// uint64 timestamp = 4;
void SharedMemoryObject::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
}
::google::protobuf::uint64 SharedMemoryObject::timestamp() const {
  // @@protoc_insertion_point(field_get:com.vip.local.cache.proto.SharedMemoryObject.timestamp)
  return timestamp_;
}
void SharedMemoryObject::set_timestamp(::google::protobuf::uint64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:com.vip.local.cache.proto.SharedMemoryObject.timestamp)
}

// uint32 opType = 5;
void SharedMemoryObject::clear_optype() {
  optype_ = 0u;
}
::google::protobuf::uint32 SharedMemoryObject::optype() const {
  // @@protoc_insertion_point(field_get:com.vip.local.cache.proto.SharedMemoryObject.opType)
  return optype_;
}
void SharedMemoryObject::set_optype(::google::protobuf::uint32 value) {
  
  optype_ = value;
  // @@protoc_insertion_point(field_set:com.vip.local.cache.proto.SharedMemoryObject.opType)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace cache
}  // namespace local
}  // namespace vip
}  // namespace com

// @@protoc_insertion_point(global_scope)
